version: '3.8'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    image: docker.io/oayouub/todo-backend:latest
    env_file:
      - ./backend/.env.local
    ports:
      - "4000:4000"
    depends_on:
      - database

  frontend:
    image: docker.io/oayouub/todo-frontend:latest
    environment:
      - REACT_APP_API_URL=http://backend:4000/api/todos
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
